### PR TITLE
Support using custom gdbscript along with breapoints and syms

### PR DESCRIPTION
**Pull request by NyaMisty**
I noticed that if I passed the gdbscript paramater, the breakpoints and syms will be ignored.
However I really need to add a 'c\n' to  the end so that the gdb will automatically continue the program everytime.
Considered that we may also override the gdbscript sometimes, I added a new config paramater called custom_gdbscript, so that if we wants to override the gdbscript, we can still pass the gdbscript to kwarg to override everything.
I've tested the code on my machine and it's working, and I'm also looking forward to your review.

### CODE REVIEW

**Comment by NyaMisty** [comment]
Note I've also changed the original 
`print(result)`
into
`print("Generated gdbscript: " + repr(result))`
image
and the output looks like this now

**Comment by matrix1001** [comment]
You remind me about this bug. I forgot to fix it. 

Normally, the script passed to gdb is `userscript` + `ctx generated script`. As a result the `continue` in `userscript` will result in that problem.

I planed to fix this by changing the order to `ctx generated script` + `userscript`.

I will consider your commit carefully.

**Comment by matrix1001** [comment]
Check line 379 in `PwnContext/core.py`，see if this change can satisfy you.

```python
kwargs['gdbscript'] += '\n{}'.format(gdbscript)
# change to 
kwargs['gdbscript'] = gdbscript + '\n' + kwargs['gdbscript']
```

**Comment by NyaMisty** [comment]
Oh my fault. I mislooked the the if statement, I'll close this now ;)

**Comment by matrix1001** [comment]
Thanks.  Fixed already.

Feel free to shoot any problems.

**Pull request closed without merging**
